import React from 'react'
import { Document, Page, Text, View, StyleSheet, Image } from '@react-pdf/renderer'

// Define a base style for all table cells to avoid repetition
const baseCellStyle = {
  borderWidth: 1,
  borderStyle: 'solid',
  borderColor: '#000',
  padding: 4,
  fontSize: 7, // Smaller font size for many columns
  wordBreak: 'break-all', // Allows long words to break and wrap
}

const styles = StyleSheet.create({
  page: { padding: 30 },
  logo: { width: 80, height: 80, marginBottom: 10 },
  header: { marginBottom: 10, textAlign: 'center' },
  headerTitle: { fontSize: 20, fontWeight: 'bold' },
  reportTitle: { fontSize: 14, marginTop: 4 },
  reportSubtitle: { fontSize: 10, color: 'gray' },
  separator: {
    borderBottomColor: '#ccc',
    borderBottomWidth: 1,
    marginVertical: 10,
  },
  view_border: {
    width: '100%',
    height: '100%',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#000',
    padding: 16,
  },
  table: {
    display: 'table',
    width: 'auto', // Let table adjust to column widths
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#000',
  },
  tableRow: { flexDirection: 'row' },

  // Header cell style combines base and bold font
  colHeaderGeneric: {
    ...baseCellStyle,
    backgroundColor: '#eee',
    fontWeight: 'bold',
  },

  // Data cell style uses the base style
  tableCell: {
    ...baseCellStyle,
  },

  // Column-specific widths
  colNum: { width: '3%' }, // N°
  colType: { width: '6%' }, // Tipo
  colClassification: { width: '7%' }, // Clasificación
  colDescription: { width: '10%' }, // Descripción
  colColor: { width: '7%' }, // Color
  colBrandModel: { width: '8%' }, // Marca / Modelo
  colSerial: { width: '7%' }, // Serial
  colMeasures: { width: '7%' }, // Medidas (cm)
  colPlateBodywork: { width: '8%' }, // Placa / Carrocería
  colEngine: { width: '6%' }, // Motor
  colYear: { width: '4%' }, // Año
  colValue: { width: '6%' }, // Valor
  colUseStatus: { width: '5%' }, // Estado
  colConservationStatus: { width: '5%' }, // Conservación
  colLocation: { width: '6%' }, // Ubicación
  colDependency: { width: '7%' }, // Dependencia
  colLevel: { width: '4%' }, // Nivel
  colAnalyst: { width: '6%' }, // Analista
  colObservation: { width: '8%' }, // Observación
  colDate: { width: '10%' }, // Fecha

  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'right',
  },
  footerText: { fontSize: 9, color: '#555' },
})

const tableHeaders = [
  { label: 'N°', style: styles.colNum },
  { label: 'Tipo', style: styles.colType },
  { label: 'Clasificación', style: styles.colClassification },
  { label: 'Descripción', style: styles.colDescription },
  { label: 'Color', style: styles.colColor },
  { label: 'Marca / Modelo', style: styles.colBrandModel },
  { label: 'Serial', style: styles.colSerial },
  { label: 'Medidas (cm)', style: styles.colMeasures },
  { label: 'Placa / Carrocería', style: styles.colPlateBodywork },
  { label: 'Motor', style: styles.colEngine },
  { label: 'Año', style: styles.colYear },
  { label: 'Valor', style: styles.colValue },
  { label: 'Estado', style: styles.colUseStatus },
  { label: 'Conservación', style: styles.colConservationStatus },
  { label: 'Ubicación', style: styles.colLocation },
  { label: 'Dependencia', style: styles.colDependency },
  { label: 'Nivel', style: styles.colLevel },
  { label: 'Analista', style: styles.colAnalyst },
  { label: 'Observación', style: styles.colObservation },
  { label: 'Fecha', style: styles.colDate },
]

const AssetsPDF = ({ inventory }) => (
  <Document>
    <Page size="A4" orientation="landscape" style={styles.page}>
      <View style={styles.view_border}>
        <View style={styles.header}>
          <Image src="/faviconassets.png" style={styles.logo} /> {/* Corrected image path */}
          <Text style={styles.headerTitle}>AssetCare</Text>
          <Text style={styles.reportTitle}>Assets Detailed Report</Text>
          <Text style={styles.reportSubtitle}>Generated by</Text>
        </View>

        <View>
          <Text style={styles.reportSubtitle}>
            Complete list of operating assets registered on the platform
          </Text>
        </View>

        <View style={styles.separator} />

        <View style={styles.table}>
          <View style={styles.tableRow}>
            {tableHeaders.map((header, i) => (
              <View key={i} style={[styles.colHeaderGeneric, header.style]}>
                <Text>{header.label}</Text>
              </View>
            ))}
          </View>

          {inventory.map((asset, index) => (
            <View style={styles.tableRow} key={index} wrap={false}>
              {' '}
              {/* wrap={false} prevents rows from breaking across pages awkwardly */}
              <View style={[styles.tableCell, styles.colNum]}>
                <Text>{index + 1}</Text>
              </View>
              <View style={[styles.tableCell, styles.colType]}>
                <Text>{asset.type}</Text>
              </View>
              <View style={[styles.tableCell, styles.colClassification]}>
                <Text>{asset.classification}</Text>
              </View>
              <View style={[styles.tableCell, styles.colDescription]}>
                <Text>{asset.description}</Text>
              </View>
              <View style={[styles.tableCell, styles.colColor]}>
                <Text>{asset.color}</Text>
              </View>
              <View style={[styles.tableCell, styles.colBrandModel]}>
                <Text>{`${asset.brand} / ${asset.model}`}</Text>
              </View>
              <View style={[styles.tableCell, styles.colSerial]}>
                <Text>{asset.serial}</Text>
              </View>
              <View style={[styles.tableCell, styles.colMeasures]}>
                <Text>{`${asset.height || ''}x${asset.width || ''}x${asset.depth || ''}`}</Text>
              </View>
              <View style={[styles.tableCell, styles.colPlateBodywork]}>
                <Text>{`${asset.plate || ''} / ${asset.bodywork || ''}`}</Text>
              </View>
              <View style={[styles.tableCell, styles.colEngine]}>
                <Text>{asset.engine}</Text>
              </View>
              <View style={[styles.tableCell, styles.colYear]}>
                <Text>{asset.year_of_the_vehicle}</Text>
              </View>
              <View style={[styles.tableCell, styles.colValue]}>
                <Text>{asset.acquisition_value}</Text>
              </View>
              <View style={[styles.tableCell, styles.colUseStatus]}>
                <Text>{asset.use_status}</Text>
              </View>
              <View style={[styles.tableCell, styles.colConservationStatus]}>
                <Text>{asset.conservation_status}</Text>
              </View>
              <View style={[styles.tableCell, styles.colLocation]}>
                <Text>{asset.physical_location}</Text>
              </View>
              <View style={[styles.tableCell, styles.colDependency]}>
                <Text>{asset.direction_dependency}</Text>
              </View>
              <View style={[styles.tableCell, styles.colLevel]}>
                <Text>{asset.level}</Text>
              </View>
              <View style={[styles.tableCell, styles.colAnalyst]}>
                <Text>{asset.analyst}</Text>
              </View>
              <View style={[styles.tableCell, styles.colObservation]}>
                <Text>{asset.observation}</Text>
              </View>
              <View style={[styles.tableCell, styles.colDate]}>
                <Text>{asset.acquisition_date}</Text>
              </View>
            </View>
          ))}
        </View>
      </View>

      <View style={styles.footer} fixed>
        <Text style={styles.footerText}>Generated on: {new Date().toLocaleString()}</Text>
      </View>
    </Page>
  </Document>
)

export default AssetsPDF
