import React from 'react'
import { Document, Page, Text, View, StyleSheet, Image } from '@react-pdf/renderer'

const baseCellStyle = {
  borderWidth: 1,
  borderStyle: 'solid',
  borderColor: '#000',
  padding: 4,
}

const styles = StyleSheet.create({
  page: { padding: 30 },
  logo: { width: 80, height: 80, marginBottom: 10 },
  header: { marginBottom: 10, textAlign: 'center' },
  headerTitle: { fontSize: 20, fontWeight: 'bold' },
  reportTitle: { fontSize: 14, marginTop: 4 },
  reportSubtitle: { fontSize: 10, color: 'gray' },
  separator: {
    borderBottomColor: '#ccc',
    borderBottomWidth: 1,
    marginVertical: 10,
  },
  view_border: {
    width: '100%',
    height: '100%',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#000',
    padding: 16,
  },
  table: {
    display: 'table',
    width: 'auto',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#000',
  },
  tableRow: { flexDirection: 'row' },
  colHeaderGeneric: {
    ...baseCellStyle,
    backgroundColor: '#eee',
    fontSize: 10,
    fontWeight: 'bold',
  },
  tableCell: {
    ...baseCellStyle,
    fontSize: 10,
    wordBreak: 'break-all',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'right',
  },
  footerText: { fontSize: 9, color: '#555' },
})

const tableHeaders = [
  'N°',
  'Tipo',
  'Clasificación',
  'Descripción',
  'Color',
  'Marca / Modelo',
  'Serial',
  'Medidas (cm)',
  'Placa / Carrocería',
  'Motor',
  'Año',
  'Valor',
  'Estado',
  'Conservación',
  'Ubicación',
  'Dependencia',
  'Nivel',
  'Analista',
  'Observación',
  'Fecha',
]

const AssetsPDF = ({ inventory }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.view_border}>
        <View style={styles.header}>
          <Image src="../../public/faviconassets.png" style={styles.logo} />
          <Text style={styles.headerTitle}>AssetCare</Text>
          <Text style={styles.reportTitle}>Assets Detailed Report</Text>
          <Text style={styles.reportSubtitle}>Generated by</Text>
        </View>

        <View style={styles.separator} />

        <View style={styles.table}>
          <View style={styles.tableRow}>
            {tableHeaders.map((header, i) => (
              <View key={i} style={styles.colHeaderGeneric}>
                <Text>{header}</Text>
              </View>
            ))}
          </View>

          {inventory.map((asset, index) => (
            <View style={styles.tableRow} key={index}>
              {[
                index + 1,
                asset.type,
                asset.classification,
                asset.description,
                asset.color,
                `${asset.brand} / ${asset.model}`,
                asset.serial,
                `${asset.height} x ${asset.width} x ${asset.depth}`,
                `${asset.plate} / ${asset.bodywork}`,
                asset.engine,
                asset.year_of_the_vehicle,
                asset.acquisition_value,
                asset.use_status,
                asset.conservation_status,
                asset.physical_location,
                asset.direction_dependency,
                asset.level,
                asset.analyst,
                asset.observation,
                asset.acquisition_date,
              ].map((cell, idx) => (
                <Text key={idx} style={styles.tableCell}>
                  {cell}
                </Text>
              ))}
            </View>
          ))}
        </View>
      </View>

      <View style={styles.footer}>
        <Text style={styles.footerText}>Generated on: {new Date().toLocaleString()}</Text>
      </View>
    </Page>
  </Document>
)

export default AssetsPDF
