import React from 'react'
import { Document, Page, Text, View, StyleSheet, Image } from '@react-pdf/renderer'

const styles = StyleSheet.create({
  page: { padding: 30 },
  title: { fontSize: 18, marginBottom: 10 },

  logo: { width: 80, height: 80, marginBottom: 10 },

  header: {
    marginBottom: 10,
    textAlign: 'center',
  },

  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
  },

  reportTitle: {
    fontSize: 14,
    marginTop: 4,
  },

  reportSubtitle: {
    fontSize: 10,
    color: 'gray',
  },

  separator: {
    borderBottomColor: '#ccc',
    borderBottomWidth: 1,
    marginVertical: 10,
  },

  view_border: {
    width: '100%',
    height: '100%',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#000',
    padding: 16,
  },

  table: {
    display: 'table',
    width: 'auto',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#000',
  },

  tableRow: { flexDirection: 'row' },

  // Columnas de encabezado
  colNumHeader: {
    width: '5%',
    backgroundColor: '#eee',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#000',
    padding: 4,
  },
  colNameHeader: {
    width: '20%',
    backgroundColor: '#eee',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#000',
    padding: 4,
  },
  colAddressHeader: {
    width: '25%',
    backgroundColor: '#eee',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#000',
    padding: 4,
  },
  colPhoneHeader: {
    width: '23%',
    backgroundColor: '#eee',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#000',
    padding: 4,
  },
  colEmailHeader: {
    width: '40%',
    backgroundColor: '#eee',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#000',
    padding: 4,
  },
  colStatusHeader: {
    width: '10%',
    backgroundColor: '#eee',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#000',
    padding: 4,
  },

  // Columnas de datos
  colNum: {
    width: '5%',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#000',
    padding: 4,
  },
  colName: {
    width: '20%',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#000',
    padding: 4,
  },
  colAddress: {
    width: '25%',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#000',
    padding: 4,
  },
  colPhone: {
    width: '23%',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#000',
    padding: 4,
  },
  colEmail: {
    width: '40%',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#000',
    padding: 4,
  },
  colStatus: {
    width: '10%',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#000',
    padding: 4,
  },

  // Estilos de texto
  tableCellHeader: { fontWeight: 'bold', fontSize: 10 },
  tableCell: {
    fontSize: 10,
    wordBreak: 'break-all',
  },

  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'right',
  },

  footerText: {
    fontSize: 9,
    color: '#555',
  },
})

const DptPDF = ({ departments }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.view_border}>
        <View style={styles.header}>
          <Image src="../../public/faviconassets.png" style={styles.logo}></Image>

          <Text style={styles.headerTitle}>AssetCare</Text>
          <Text style={styles.reportTitle}>Department List Report</Text>
          <Text style={styles.reportSubtitle}>Generated by </Text>
        </View>

        <View>
          <Text style={styles.reportSubtitle}>
            Complete list of operating departments registered on the platform
          </Text>
        </View>

        <View style={styles.separator} />

        <View style={styles.table}>
          <View style={styles.tableRow}>
            <View style={styles.colNumHeader}>
              <Text style={styles.tableCellHeader}>N°</Text>
            </View>
            <View style={styles.colNameHeader}>
              <Text style={styles.tableCellHeader}>Name</Text>
            </View>
            <View style={styles.colAddressHeader}>
              <Text style={styles.tableCellHeader}>Address</Text>
            </View>
            <View style={styles.colPhoneHeader}>
              <Text style={styles.tableCellHeader}>Phone</Text>
            </View>
            <View style={styles.colEmailHeader}>
              <Text style={styles.tableCellHeader}>Email</Text>
            </View>
            <View style={styles.colStatusHeader}>
              <Text style={styles.tableCellHeader}>Status</Text>
            </View>
          </View>

          {departments.map((dept, index) => (
            <View style={styles.tableRow} key={index}>
              <View style={styles.colNum}>
                <Text style={styles.tableCell}>{index + 1}</Text>
              </View>
              <View style={styles.colName}>
                <Text style={styles.tableCell}>{dept.name}</Text>
              </View>
              <View style={styles.colAddress}>
                <Text style={styles.tableCell}>{dept.address}</Text>
              </View>
              <View style={styles.colPhone}>
                <Text style={styles.tableCell}>{dept.phone}</Text>
              </View>
              <View style={styles.colEmail}>
                <Text style={styles.tableCell}>{dept.email}</Text>
              </View>
              <View style={styles.colStatus}>
                <Text style={styles.tableCell}>{dept.operational_status}</Text>
              </View>
            </View>
          ))}
        </View>
      </View>
      <View style={styles.footer}>
        <Text style={styles.footerText}> Generated on: {new Date().toLocaleString()}</Text>
      </View>
    </Page>
  </Document>
)

export default DptPDF
